FIPI_DIR = r'D:\fund_tracker_psx\data\fipi'
LIPI_DIR = r'D:\fund_tracker_psx\data\lipi'
PROCESSED_FIPI_LIPI_DIR = r'D:\fund_tracker_psx\data\processed_fipi_lipi'
STOCKS_DIR = r'D:\fund_tracker_psx\data\stocks'
RAW_STOCKS_DIR = r'D:\fund_tracker_psx\data\raw_data'
QUOTATION_DATA_DIR = r'D:\fund_tracker_psx\data\quotation_data'